In [ ]:
input_game_str: str = """
[Event "Live Chess"]
[Site "Chess.com"]
[Date "2026.02.23"]
[Round "-"]
[White "Smothered_mate1964"]
[Black "nielsenmendescampos"]
[Result "1-0"]
[CurrentPosition "rn1qkb1r/pp2pBpp/2p2n2/4N3/3P4/2N5/PPP3PP/R1BbK2R b KQkq - 0 8"]
[Timezone "UTC"]
[ECO "B15"]
[ECOUrl "https://www.chess.com/openings/Caro-Kann-Defense-von-Hennig-Gambit"]
[UTCDate "2026.02.23"]
[UTCTime "17:19:24"]
[WhiteElo "1103"]
[BlackElo "1067"]
[TimeControl "180"]
[Termination "Smothered_mate1964 won by checkmate"]
[StartTime "17:19:24"]
[EndDate "2026.02.23"]
[EndTime "17:19:43"]
[Link "https://www.chess.com/analysis/game/live/165106586944/analysis"]
[WhiteUrl "https://www.chess.com/bundles/web/images/noavatar_l.84a92436.gif"]
[WhiteCountry "2"]
[WhiteTitle ""]
[BlackUrl "https://images.chesscomfiles.com/uploads/v1/user/145760667.d645313d.50x50o.7374f87d431b.png"]
[BlackCountry "27"]
[BlackTitle ""]

1. e4 {[%clk 0:02:59.9]} 1... c6 {[%clk 0:02:58.7]} 2. d4 {[%clk 0:02:58.8]}
2... d5 {[%clk 0:02:58.6]} 3. Nc3 {[%clk 0:02:58.3]} 3... dxe4 {[%clk
0:02:55.9]} 4. Bc4 {[%clk 0:02:57.6]} 4... Nf6 {[%clk 0:02:52.3]} 5. f3 {[%clk
0:02:57.1]} 5... exf3 {[%clk 0:02:51]} 6. Nxf3 {[%clk 0:02:57]} 6... Bg4 {[%clk
0:02:49.8]} 7. Ne5 {[%clk 0:02:56.4]} 7... Bxd1 {[%clk 0:02:47.4]} 8. Bxf7#
{[%clk 0:02:55.6][%c_effect
e1;square;e1;type;Winner;animated;true,e8;square;e8;type;CheckmateBlack;animated;true]}
1-0
"""

In [ ]:
input_game_str: str = """
[Event "Live Chess"]
[Site "Chess.com"]
[Date "2026.02.20"]
[Round "-"]
[White "nielsenmendescampos"]
[Black "hiperhidra603"]
[Result "1/2-1/2"]
[CurrentPosition "6k1/6P1/6K1/8/8/8/8/8 b - - 2 65"]
[Timezone "UTC"]
[ECO "A04"]
[ECOUrl "https://www.chess.com/openings/Reti-Opening-Kingside-Fianchetto-Variation-2.g3-Bg7-3.d4"]
[UTCDate "2026.02.20"]
[UTCTime "19:16:53"]
[WhiteElo "1232"]
[BlackElo "1230"]
[TimeControl "600"]
[Termination "Game drawn by stalemate"]
[StartTime "19:16:53"]
[EndDate "2026.02.20"]
[EndTime "19:31:50"]
[Link "https://www.chess.com/analysis/game/live/164973965638/analysis"]
[WhiteUrl "https://images.chesscomfiles.com/uploads/v1/user/145760667.d645313d.50x50o.7374f87d431b.png"]
[WhiteCountry "27"]
[WhiteTitle ""]
[BlackUrl "https://images.chesscomfiles.com/uploads/v1/user/167973295.7f23889e.50x50o.afec0a4ca766.jpeg"]
[BlackCountry "69"]
[BlackTitle ""]

1. d4 {[%clk 0:09:56.9]} 1... g6 {[%clk 0:09:58.2]} 2. Nf3 {[%clk 0:09:53.7]}
2... Bg7 {[%clk 0:09:56.5]} 3. g3 {[%clk 0:09:53.3]} 3... e6 {[%clk 0:09:53.3]}
4. Bg2 {[%clk 0:09:52.7]} 4... Nf6 {[%clk 0:09:52.1]} 5. c4 {[%clk 0:09:51.8]}
5... d5 {[%clk 0:09:50.2]} 6. Nbd2 {[%clk 0:09:44.2]} 6... dxc4 {[%clk 0:09:48]}
7. Nxc4 {[%clk 0:09:42.9]} 7... O-O {[%clk 0:09:42.1]} 8. O-O {[%clk 0:09:41.3]}
8... h6 {[%clk 0:09:35.8]} 9. Re1 {[%clk 0:09:40]} 9... Nc6 {[%clk 0:09:30.2]}
10. a3 {[%clk 0:08:47.6]} 10... Bd7 {[%clk 0:09:29]} 11. Rb1 {[%clk 0:08:46.4]}
11... Qc8 {[%clk 0:09:27.4]} 12. e4 {[%clk 0:08:36.4]} 12... Re8 {[%clk
0:09:21.4]} 13. e5 {[%clk 0:08:27.6]} 13... Nd5 {[%clk 0:09:15.6]} 14. Be3
{[%clk 0:08:22.3]} 14... f6 {[%clk 0:09:11.8]} 15. b4 {[%clk 0:07:52.7]} 15...
fxe5 {[%clk 0:09:09.4]} 16. Ncxe5 {[%clk 0:07:38]} 16... Nxe5 {[%clk 0:09:02]}
17. Nxe5 {[%clk 0:07:32]} 17... Bxe5 {[%clk 0:08:52.6]} 18. dxe5 {[%clk
0:07:29.7]} 18... Nxe3 {[%clk 0:08:50.2]} 19. Rxe3 {[%clk 0:07:28]} 19... Rd8
{[%clk 0:08:46.8]} 20. Qg4 {[%clk 0:06:37.2]} 20... Kg7 {[%clk 0:08:36.2]} 21.
Rbe1 {[%clk 0:06:15.8]} 21... c5 {[%clk 0:08:26.1]} 22. h4 {[%clk 0:06:12.5]}
22... cxb4 {[%clk 0:08:19.5]} 23. axb4 {[%clk 0:06:09.7]} 23... a5 {[%clk
0:07:54.8]} 24. h5 {[%clk 0:06:07.3]} 24... g5 {[%clk 0:07:52.5]} 25. Qe4 {[%clk
0:05:57.3]} 25... Be8 {[%clk 0:07:43.9]} 26. bxa5 {[%clk 0:05:51.3]} 26... Rxa5
{[%clk 0:07:41.4]} 27. Qxb7+ {[%clk 0:05:48.6]} 27... Qxb7 {[%clk 0:07:34.3]}
28. Bxb7 {[%clk 0:05:48.5]} 28... Bxh5 {[%clk 0:07:29.8]} 29. Rc1 {[%clk
0:05:43.8]} 29... Rd7 {[%clk 0:06:59.8]} 30. Bc8 {[%clk 0:05:34.5]} 30... Rda7
{[%clk 0:06:52.4]} 31. Bxe6 {[%clk 0:05:30.2]} 31... Re7 {[%clk 0:06:29.2]} 32.
Bf5 {[%clk 0:05:00.8]} 32... Raxe5 {[%clk 0:06:03.7]} 33. Rxe5 {[%clk
0:04:58.8]} 33... Rxe5 {[%clk 0:06:02.8]} 34. Rc7+ {[%clk 0:04:58.4]} 34... Kf6
{[%clk 0:05:59.2]} 35. g4 {[%clk 0:04:39.2]} 35... Be8 {[%clk 0:05:52]} 36. Rh7
{[%clk 0:04:34.1]} 36... Re1+ {[%clk 0:05:33.1]} 37. Kg2 {[%clk 0:04:32.5]}
37... Bc6+ {[%clk 0:05:31.5]} 38. f3 {[%clk 0:04:30.4]} 38... Ke5 {[%clk
0:05:07.8]} 39. Rxh6 {[%clk 0:04:26.8]} 39... Bd5 {[%clk 0:04:58]} 40. Rh7
{[%clk 0:04:12]} 40... Kf4 {[%clk 0:04:55.1]} 41. Rd7 {[%clk 0:03:59.3]} 41...
Bxf3+ {[%clk 0:04:52.6]} 42. Kf2 {[%clk 0:03:55.3]} 42... Re2+ {[%clk
0:04:44.5]} 43. Kf1 {[%clk 0:03:48.1]} 43... Re5 {[%clk 0:04:18.9]} 44. Rd4+
{[%clk 0:03:44.5]} 44... Be4 {[%clk 0:04:17.2]} 45. Kf2 {[%clk 0:03:26.9]} 45...
Re7 {[%clk 0:03:55.1]} 46. Bxe4 {[%clk 0:03:21.4]} 46... Rxe4 {[%clk 0:03:54]}
47. Rxe4+ {[%clk 0:03:20.6]} 47... Kxe4 {[%clk 0:03:53.3]} 48. Kg3 {[%clk
0:03:20.5]} 48... Ke5 {[%clk 0:03:50.5]} 49. Kf3 {[%clk 0:03:20.1]} 49... Kf6
{[%clk 0:03:49.1]} 50. Ke4 {[%clk 0:03:19.4]} 50... Kg6 {[%clk 0:03:45]} 51. Ke5
{[%clk 0:03:18.4]} 51... Kg7 {[%clk 0:03:40.6]} 52. Kf5 {[%clk 0:03:16.4]} 52...
Kh6 {[%clk 0:03:39.8]} 53. Kf6 {[%clk 0:03:14.3]} 53... Kh7 {[%clk 0:03:36.4]}
54. Kxg5 {[%clk 0:03:13.6]} 54... Kg7 {[%clk 0:03:34.8]} 55. Kh5 {[%clk
0:03:12.3]} 55... Kh7 {[%clk 0:03:33.8]} 56. g5 {[%clk 0:03:09.9]} 56... Kg7
{[%clk 0:03:32.1]} 57. g6 {[%clk 0:02:53.3]} 57... Kh8 {[%clk 0:03:25.6]} 58.
Kg5 {[%clk 0:02:49.2]} 58... Kg7 {[%clk 0:03:24.4]} 59. Kf5 {[%clk 0:02:47.7]}
59... Kg8 {[%clk 0:03:21.4]} 60. Kf6 {[%clk 0:02:45.3]} 60... Kf8 {[%clk
0:03:12.4]} 61. Kg5 {[%clk 0:02:38.7]} 61... Kg7 {[%clk 0:03:11.2]} 62. Kf5
{[%clk 0:02:37.4]} 62... Kg8 {[%clk 0:03:06.8]} 63. Kf6 {[%clk 0:02:34.9]} 63...
Kf8 {[%clk 0:03:05.3]} 64. g7+ {[%clk 0:02:33.6]} 64... Kg8 {[%clk 0:03:04.5]}
65. Kg6 {[%clk 0:02:32.6][%c_effect
g8;square;g8;type;DrawBlack;animated;true,g6;square;g6;type;DrawWhite;animated;true]}
1/2-1/2
"""

In [ ]:
input_game_str: str = """
[Event "casual blitz game"]
[Site "https://lichess.org/OH7Be7RS"]
[Date "2026.02.25"]
[Round "-"]
[White "Anonymous"]
[Black "Anonymous"]
[Result "1-0"]
[GameId "OH7Be7RS"]
[UTCDate "2026.02.25"]
[UTCTime "19:03:46"]
[WhiteElo "?"]
[BlackElo "?"]
[Variant "Standard"]
[TimeControl "180+0"]
[ECO "A45"]
[Opening "Indian Defense: Accelerated London System"]
[Termination "Normal"]
[Annotator "lichess.org"]

1. d4 Nf6 2. Bf4 { A45 Indian Defense: Accelerated London System } g6 3. e3 Bg7 4. Bd3 O-O 5. c3 d5 6. Qc2 c6 7. h3 Nbd7 8. Bh2 Nb6 9. f4 Ne4 10. Nd2 Bf5 11. g4 Nxd2 12. Bxf5 Nbc4 13. Bd3 Qc7 14. b3 Na3 15. Qxd2 e5 16. Qb2 f5 17. Qxa3 e4 18. Be2 fxg4 19. Bxg4 h5 20. Be2 Qb6 21. O-O-O { Black resigns. } 1-0
"""

In [ ]:
input_game_str: str = """

[Event "Live Chess"]
[Site "Chess.com"]
[Date "2026.02.25"]
[Round "-"]
[White "nielsenmendescampos"]
[Black "TheDarkKnightj316"]
[Result "1-0"]
[CurrentPosition "2r1r1k1/p1q2ppp/2p5/5p2/5B2/6P1/PP3PBP/R2QR1K1 w - - 0 20"]
[Timezone "UTC"]
[ECO "D02"]
[ECOUrl "https://www.chess.com/openings/Queens-Pawn-Opening-Krause-Variation-3.c3-Nc6"]
[UTCDate "2026.02.25"]
[UTCTime "18:43:51"]
[WhiteElo "1029"]
[BlackElo "1018"]
[TimeControl "180"]
[Termination "nielsenmendescampos won by resignation"]
[StartTime "18:43:51"]
[EndDate "2026.02.25"]
[EndTime "18:45:39"]
[Link "https://www.chess.com/analysis/game/live/165202585552/analysis"]
[WhiteUrl "https://images.chesscomfiles.com/uploads/v1/user/145760667.d645313d.50x50o.7374f87d431b.png"]
[WhiteCountry "27"]
[WhiteTitle ""]
[BlackUrl "https://images.chesscomfiles.com/uploads/v1/user/98987204.969ed485.50x50o.9ed4cfe02e0b.jpg"]
[BlackCountry "2"]
[BlackTitle ""]

1. d4 {[%clk 0:02:56.6]} 1... d5 {[%clk 0:02:59.3]} 2. Nf3 {[%clk 0:02:51.2]}
2... c5 {[%clk 0:02:58]} 3. c3 {[%clk 0:02:49.7]} 3... Nc6 {[%clk 0:02:55.8]} 4.
e3 {[%clk 0:02:46.3]} 4... e6 {[%clk 0:02:53.7]} 5. g3 {[%clk 0:02:44.9]} 5...
Bd6 {[%clk 0:02:52.9]} 6. Bg2 {[%clk 0:02:44.8]} 6... Bd7 {[%clk 0:02:51.6]} 7.
O-O {[%clk 0:02:44.3]} 7... Nge7 {[%clk 0:02:51.1]} 8. Re1 {[%clk 0:02:43.7]}
8... O-O {[%clk 0:02:50.4]} 9. Nbd2 {[%clk 0:02:43]} 9... Qc7 {[%clk 0:02:49.4]}
10. e4 {[%clk 0:02:41.3]} 10... Rfe8 $4 {[%clk 0:02:40.4][%c_effect
e8;square;e8;type;Blunder;persistent;true]} 11. e5 $1 {[%clk 0:02:40.3][%c_effect
e5;square;e5;type;GreatFind;persistent;true]} 11... Nxe5 $6 {[%clk
0:02:36.9][%c_effect e5;square;e5;type;Inaccuracy;persistent;true]} 12. dxe5
{[%clk 0:02:37.3]} 12... Bxe5 {[%clk 0:02:35.2]} 13. Nxe5 {[%clk 0:02:36]} 13...
d4 {[%clk 0:02:29.3]} 14. cxd4 {[%clk 0:02:31.1]} 14... cxd4 {[%clk 0:02:28.4]}
15. Ndf3 {[%clk 0:02:26.4]} 15... Rac8 {[%clk 0:02:23]} 16. Nxd4 {[%clk
0:02:22.2]} 16... Nf5 {[%clk 0:02:20.8]} 17. Nxf5 {[%clk 0:02:20.7]} 17... exf5
{[%clk 0:02:19.6]} 18. Bf4 {[%clk 0:02:14.9]} 18... Bc6 $6 {[%clk
0:02:09.4][%c_effect c6;square;c6;type;Inaccuracy;persistent;true]} 19. Nxc6
{[%clk 0:02:13.7]} 19... bxc6 {[%clk 0:02:08][%c_effect
g1;square;g1;type;Winner;animated;true,g8;square;g8;type;ResignBlack;animated;true]}
1-0
"""

In [ ]:
input_game_str: str = """
[Event "rated blitz game"]
[Site "https://lichess.org/iuIjdeYr"]
[Date "2026.03.12"]
[Round "-"]
[White "Pyke333"]
[Black "nielsencampos"]
[Result "0-1"]
[GameId "iuIjdeYr"]
[UTCDate "2026.03.12"]
[UTCTime "20:23:49"]
[WhiteElo "1435"]
[BlackElo "1441"]
[WhiteRatingDiff "-5"]
[BlackRatingDiff "+75"]
[Variant "Standard"]
[TimeControl "180+0"]
[ECO "A45"]
[Opening "Trompowsky Attack"]
[Termination "Normal"]
[Annotator "lichess.org"]

1. d4 { [%eval 0.15] [%clk 0:03:00] } 1... Nf6 { [%eval 0.15] [%clk 0:03:00] } 2. Bg5 { [%eval 0.0] [%clk 0:02:58] } { A45 Trompowsky Attack } 2... h6 { [%eval 0.2] [%clk 0:02:55] } 3. Bh4 { [%eval 0.0] [%clk 0:02:57] } 3... g5 { [%eval 0.08] [%clk 0:02:53] } 4. Bg3 { [%eval 0.0] [%clk 0:02:56] } 4... d5 { [%eval 0.15] [%clk 0:02:51] } 5. e3 { [%eval 0.15] [%clk 0:02:54] } 5... Bg7 { [%eval 0.13] [%clk 0:02:51] } 6. Nc3 { [%eval 0.08] [%clk 0:02:52] } 6... Bf5 { [%eval 0.54] [%clk 0:02:49] } 7. Bd3 { [%eval 0.4] [%clk 0:02:50] } 7... Bg6? { (0.40 → 1.70) Mistake. Ne4 was best. } { [%eval 1.7] [%clk 0:02:46] } (7... Ne4 8. Bxe4 dxe4 9. f3 c5 10. fxe4 Bg6 11. Nf3 cxd4 12. exd4) 8. Bxg6 { [%eval 1.67] [%clk 0:02:48] } 8... fxg6 { [%eval 1.68] [%clk 0:02:46] } 9. Nf3 { [%eval 1.8] [%clk 0:02:44] } 9... Qd7 { [%eval 2.04] [%clk 0:02:45] } 10. Ne5 { [%eval 2.0] [%clk 0:02:43] } 10... Qe6?! { (2.00 → 2.96) Inaccuracy. Qf5 was best. } { [%eval 2.96] [%clk 0:02:45] } (10... Qf5 11. Qd3 Qxd3 12. cxd3 c6 13. Nxg6 Rg8 14. h4 Ng4 15. hxg5 hxg5 16. Ne5) 11. Nxg6 { [%eval 2.38] [%clk 0:02:39] } 11... Rg8 { [%eval 2.18] [%clk 0:02:43] } 12. Ne5 { [%eval 2.15] [%clk 0:02:37] } 12... Nc6?! { (2.15 → 3.20) Inaccuracy. c6 was best. } { [%eval 3.2] [%clk 0:02:40] } (12... c6 13. a4 Na6 14. h4 O-O-O 15. hxg5 hxg5 16. Qe2 Nb4 17. O-O-O Rh8 18. Rxh8) 13. Nxc6?! { (3.20 → 1.89) Inaccuracy. Nb5 was best. } { [%eval 1.89] [%clk 0:02:35] } (13. Nb5 Kd8 14. Nd3 Qf5 15. Nxc7 Rc8 16. Qf3 e6 17. Qxf5 exf5 18. Ne6+ Ke7) 13... Qxc6 { [%eval 2.06] [%clk 0:02:40] } 14. Qd3 { [%eval 2.06] [%clk 0:02:33] } 14... O-O-O?! { (2.06 → 2.75) Inaccuracy. a6 was best. } { [%eval 2.75] [%clk 0:02:39] } (14... a6 15. Qg6+ Kd7 16. h4 gxh4 17. Rxh4 Raf8 18. O-O-O Kc8 19. a3 e6 20. Kb1) 15. O-O-O?! { (2.75 → 1.60) Inaccuracy. Nb5 was best. } { [%eval 1.6] [%clk 0:02:28] } (15. Nb5 Kd7 16. Nxa7 Qc4 17. Qxc4 dxc4 18. Nb5 c6 19. Nc3 Ra8 20. Ke2 b5) 15... e6? { (1.60 → 2.92) Mistake. a6 was best. } { [%eval 2.92] [%clk 0:02:38] } (15... a6 16. h4 g4 17. Kb1 Kb8 18. a3 Nh5 19. Bh2 Bh8 20. Qf5 Nf6 21. f3) 16. e4?? { (2.92 → 0.12) Blunder. Nb5 was best. } { [%eval 0.12] [%clk 0:02:21] } (16. Nb5 Qa6 17. Nxc7 Qxa2 18. Nxe6 Ne4 19. c3 Rd7 20. f3 Nxg3 21. hxg3 Bf8) 16... dxe4?! { (0.12 → 0.92) Inaccuracy. Nxe4 was best. } { [%eval 0.92] [%clk 0:02:34] } (16... Nxe4 17. Nxe4 dxe4 18. Qe3 Qd5 19. c3 h5 20. h3 h4 21. Bh2 Rdf8 22. Kb1) 17. Qe3?! { (0.92 → 0.06) Inaccuracy. Qb5 was best. } { [%eval 0.06] [%clk 0:02:10] } (17. Qb5 Qxb5 18. Nxb5 Nd5 19. Nxa7+ Kb8 20. Nb5 h5 21. Rhe1 Rdf8 22. Rd2 h4) 17... Nd5 { [%eval -0.03] [%clk 0:02:30] } 18. Nxe4?? { (-0.03 → -6.24) Blunder. Qxe4 was best. } { [%eval -6.24] [%clk 0:02:04] } (18. Qxe4 Nxc3 19. Qxc6 Nxa2+ 20. Kb1 bxc6 21. Kxa2 Bxd4 22. Rhe1 h5 23. Rxe6 h4) 18... Nxe3 { [%eval -6.42] [%clk 0:02:28] } 19. fxe3 { [%eval -6.24] [%clk 0:02:01] } 19... Qxe4 { [%eval -6.19] [%clk 0:02:24] } { White resigns. } 0-1
"""

In [1]:
input_game_str: str = "1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4 4. d4 d6 5. h3 Nh6 6. e6 *"

In [2]:
from io import StringIO

from chess import Board, Move
from chess.pgn import Game, GameNode, StringExporter, read_game

In [3]:
source_game: Game = read_game(StringIO(input_game_str))
source_game_node: GameNode = source_game
target_game: Game = Game()
target_game_node: GameNode = target_game
board: Board = source_game_node.board().copy(stack=False)
board_str: str = str(board)
move_number: int = board.fullmove_number

In [4]:
from chess_reporter.domain.position import PositionContext

In [5]:
from chess_reporter.engine import EngineManager

In [15]:
position: PositionContext = PositionContext(board=board)

In [16]:
engine: EngineManager = EngineManager(context=position)

2026-03-17 03:50:05 | INFO     | chess_reporter.engine.engine_manager:96 - Engine config data:
{'name_version': 'Stockfish 18', 'threads': 4, 'hash_table_mb': 2048, 'depth': 30, 'multipv': 7, 'analyses': 7, 'parallelism': True, 'status': <DataStatus.COMPLETED: 'completed'>, 'id': '13232c92f5226e2d3b36ee97b1fce57e90217a9ad43b693619148a49875990f44c39741092f78d589e8dc1e90685e7e34930b1b92136fb1c8fa7b6edf0ffda17'}

In [17]:
results = engine.analyze()

In [18]:
from pandas import DataFrame

In [19]:
dataframe = DataFrame([
    {
        "analysis_run": row.analysis_run,
        "variation_rank": row.variation_rank,
        "evaluation": row.evaluation,
        "search_depth": row.search_depth,
        "selective_search_depth": row.selective_search_depth,
        "hash_table_usage": row.hash_table_usage,
        "time_in_seconds": row.time_in_seconds,
        "started_analysis_at": row.started_analysis_at,
        "finished_analysis_at": row.finished_analysis_at,
    }
    for row in results])

In [20]:
dataframe

,analysis_run,variation_rank,evaluation,search_depth,selective_search_depth,hash_table_usage,time_in_seconds,started_analysis_at,finished_analysis_at
0,1,1,+0.92,30,40,73.7,0.297240,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845075+00:00
1,1,2,+1.64,30,69,73.7,0.297240,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845116+00:00
2,1,3,+2.04,30,49,73.7,0.297241,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845126+00:00
3,1,4,+2.18,30,54,73.7,0.297241,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845133+00:00
4,1,5,+2.44,30,58,73.7,0.297241,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845140+00:00
5,1,6,+2.83,30,47,73.7,0.297241,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845146+00:00
6,1,7,+3.14,30,58,73.7,0.297241,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845152+00:00
7,2,1,+0.93,30,53,83.5,0.389682,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306401+00:00
8,2,2,+1.74,30,65,83.5,0.389685,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306434+00:00
9,2,3,+2.12,30,58,83.5,0.389686,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306445+00:00
10,2,4,+2.12,30,59,83.5,0.389686,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306452+00:00
11,2,5,+2.39,30,46,83.5,0.389686,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306459+00:00
12,2,6,+2.88,30,47,83.5,0.389686,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306465+00:00
13,2,7,+3.15,30,46,83.5,0.389686,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306485+00:00
14,3,1,+0.85,30,58,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856799+00:00
15,3,2,+1.66,30,67,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856829+00:00
16,3,3,+1.96,30,60,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856840+00:00
17,3,4,+2.08,30,66,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856847+00:00
18,3,5,+2.47,30,54,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856853+00:00
19,3,6,+2.86,30,60,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856871+00:00
20,3,7,+3.15,30,74,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856878+00:00
21,4,1,+0.94,30,54,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581517+00:00
22,4,2,+1.78,30,56,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581574+00:00
23,4,3,+2.01,30,62,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581590+00:00
24,4,4,+2.05,30,65,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581601+00:00
25,4,5,+2.46,30,57,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581610+00:00
26,4,6,+2.88,30,56,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581620+00:00
27,4,7,+3.15,30,71,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581630+00:00
28,6,1,+0.83,30,52,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343397+00:00
29,6,2,+1.69,30,46,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343442+00:00
30,6,3,+1.82,30,64,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343458+00:00
31,6,4,+2.14,30,64,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343469+00:00
32,6,5,+2.44,30,50,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343480+00:00
33,6,6,+2.87,30,44,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343490+00:00
34,6,7,+3.09,30,70,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343500+00:00
35,5,1,+0.93,30,56,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412318+00:00
36,5,2,+1.69,30,62,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412349+00:00
37,5,3,+2.03,30,54,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412358+00:00
38,5,4,+2.28,30,62,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412365+00:00
39,5,5,+2.43,30,48,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412385+00:00
40,5,6,+2.83,30,52,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412391+00:00
41,5,7,+3.13,30,58,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412397+00:00
42,7,1,+0.91,30,57,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137122+00:00
43,7,2,+1.77,30,63,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137160+00:00
44,7,3,+1.83,30,83,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137168+00:00
45,7,4,+2.28,30,66,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137174+00:00
46,7,5,+2.51,30,55,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137178+00:00
47,7,6,+2.94,30,62,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137192+00:00
48,7,7,+3.25,30,54,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137197+00:00

In [21]:
dataframe[dataframe["variation_rank"] == 1]

,analysis_run,variation_rank,evaluation,search_depth,selective_search_depth,hash_table_usage,time_in_seconds,started_analysis_at,finished_analysis_at
0,1,1,+0.92,30,40,73.7,0.297240,2026-03-17 03:50:07.897947+00:00,2026-03-17 03:55:05.845075+00:00
7,2,1,+0.93,30,53,83.5,0.389682,2026-03-17 03:50:07.898731+00:00,2026-03-17 03:56:38.306401+00:00
14,3,1,+0.85,30,58,85.4,0.418260,2026-03-17 03:50:07.898646+00:00,2026-03-17 03:57:06.856799+00:00
21,4,1,+0.94,30,54,85.8,0.424751,2026-03-17 03:55:06.518829+00:00,2026-03-17 04:02:11.581517+00:00
28,6,1,+0.83,30,52,72.7,0.324429,2026-03-17 03:57:07.586468+00:00,2026-03-17 04:02:32.343397+00:00
35,5,1,+0.93,30,56,79.7,0.380922,2026-03-17 03:56:39.136762+00:00,2026-03-17 04:03:00.412318+00:00
42,7,1,+0.91,30,57,83.2,0.244392,2026-03-17 04:02:12.334902+00:00,2026-03-17 04:06:17.137122+00:00

In [23]:
results[0]

EngineAnalysis(context=EngineContext(position_context=PositionContext(board=Board('r1bqkb1r/ppp1pppp/2npP2n/8/3P4/5N1P/PPP2PP1/RNBQKB1R b KQkq - 0 6'), game_outcome_input=None, fen='r1bqkb1r/ppp1pppp/2npP2n/8/3P4/5N1P/PPP2PP1/RNBQKB1R b KQkq - 0 6', chess960=False, ascii_board='r . b q k b . r\np p p . p p p p\n. . n p P . . n\n. . . . . . . .\n. . . P . . . .\n. . . . . N . P\nP P P . . P P .\nR N B Q K B . R', game_termination=<GameTermination.ONGOING: 'ongoing'>, game_result=<GameResult.ONGOING: 'ongoing'>, turn=<PositionTurn.BLACK: 'black'>, white_material=3900, white_piece_count=16, black_material=3900, black_piece_count=16, overall_material=7800, overall_piece_count=32, material_balance=0, piece_count_balance=0, material_game_phase=<GamePhase.OPENING: 'opening'>, legal_moves_count=23, captures_count=3), analysis_run=1), started_analysis_at=datetime.datetime(2026, 3, 17, 3, 50, 7, 897947, tzinfo=datetime.timezone.utc), finished_analysis_at=datetime.datetime(2026, 3, 17, 3, 55, 5, 845075, tzinfo=datetime.timezone.utc), info_dict={'score': PovScore(Cp(-92), BLACK), 'pv': [Move.from_uci('f7e6'), Move.from_uci('h3h4'), Move.from_uci('d8d7'), Move.from_uci('b1c3'), Move.from_uci('h6f7'), Move.from_uci('f1c4'), Move.from_uci('a7a6'), Move.from_uci('c4e2'), Move.from_uci('d6d5'), Move.from_uci('c1f4'), Move.from_uci('b7b6'), Move.from_uci('d1d3'), Move.from_uci('e6e5'), Move.from_uci('d4e5'), Move.from_uci('e7e6'), Move.from_uci('e1c1'), Move.from_uci('c8b7'), Move.from_uci('f3g5'), Move.from_uci('f7g5'), Move.from_uci('f4g5'), Move.from_uci('c6e5'), Move.from_uci('d3h3'), Move.from_uci('h7h5'), Move.from_uci('h1e1'), Move.from_uci('f8d6'), Move.from_uci('c1b1'), Move.from_uci('d7f7'), Move.from_uci('f2f4'), Move.from_uci('e5g4'), Move.from_uci('e2g4'), Move.from_uci('h5g4'), Move.from_uci('h3g4'), Move.from_uci('e8g8'), Move.from_uci('h4h5'), Move.from_uci('f7f5'), Move.from_uci('g4e2'), Move.from_uci('a8e8'), Move.from_uci('h5h6')], 'depth': 30, 'seldepth': 40, 'time': 297.24, 'nodes': 285842626, 'nps': 961655, 'tbhits': 0, 'multipv': 1, 'currmove': Move.from_uci('h6g4'), 'currmovenumber': 23, 'hashfull': 737, 'string': 'Network replica 1: Shared memory.'}, mate_in_centipawns=100000, analysis_run=1, variation_rank=1, evaluation_type=<EngineEvaluationType.NORMAL: 'normal'>, search_depth=30, selective_search_depth=40, total_positions_evaluated=285842626, nodes_per_second=961655, ebf=1.9136869696979641, tablebase_hits=0, cpu_load=None, hash_table_usage=73.7, time_in_seconds=0.29724, message='Network replica 1: Shared memory.', score_type=<EngineScoreType.CENTIPAWNS: 'centipawns'>, score_value=92, score_in_centipawns=92, evaluation='+0.92', win_probability_balance=46.1)

In [13]:
source_game_node = source_game_node.next()
move_text_string_exporter: StringExporter = StringExporter(headers=False, variations=False, comments=False)
move_text: str = ""

In [14]:
while True:
    move: Move = source_game_node.move
    move_ply: int = source_game_node.ply()
    move_uci: str = source_game_node.uci()
    move_san: str = source_game_node.san()
    move_comment: str = source_game_node.comment
    target_game_node = target_game_node.add_main_variation(move)
    move_text = target_game_node.accept(move_text_string_exporter).strip()
    source_game_node = source_game_node.next()
    #print(f" * board:\n{str(board)}")
    print(f" * move_number: {move_number}")
    print(f" * move_ply: {move_ply}")
    print(f" * move_uci: {move_uci}")
    print(f" * move_comment: {move_comment}")
    print(f" * move_text: {move_text}")
    print("")
    
    if source_game_node is None:
        break

    board = source_game_node.board().copy(stack=False)
    board_str = str(board)
    move_number = board.fullmove_number

 * move_number: 1
 * move_ply: 1
 * move_uci: e2e4
 * move_comment:
 * move_text: 1. e4

 * move_number: 2
 * move_ply: 2
 * move_uci: b8c6
 * move_comment:
 * move_text: 1. e4 Nc6

 * move_number: 2
 * move_ply: 3
 * move_uci: g1f3
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3

 * move_number: 3
 * move_ply: 4
 * move_uci: g8f6
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6

 * move_number: 3
 * move_ply: 5
 * move_uci: e4e5
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5

 * move_number: 4
 * move_ply: 6
 * move_uci: f6g4
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4

 * move_number: 4
 * move_ply: 7
 * move_uci: d2d4
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4 4. d4

 * move_number: 5
 * move_ply: 8
 * move_uci: d7d6
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4 4. d4 d6

 * move_number: 5
 * move_ply: 9
 * move_uci: h2h3
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4 4. d4 d6 5. h3

 * move_number: 6
 * move_ply: 10
 * move_uci: g4h6
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4 4. d4 d6 5. h3 Nh6

 * move_number: 6
 * move_ply: 11
 * move_uci: e5e6
 * move_comment:
 * move_text: 1. e4 Nc6 2. Nf3 Nf6 3. e5 Ng4 4. d4 d6 5. h3 Nh6 6. e6